version: "3.9"
services:
  app:
    image: node:18.13
    volumes:
      - "./app:/mnt/app"
    working_dir: "/mnt/app"
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true npm start || (\
          echo '⛔ `npm start` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports:
      - '3000:3000'
    networks:
      - app-network
 
  sync:
    image: node:18.13
    volumes:
      - "./sync:/mnt/sync"
    working_dir: "/mnt/sync"
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true npm start || (\
          echo '⛔ `npm start` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports:
      - '4000:4000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
